### PR TITLE
Upgrade dependencies, require PHP 7.1

### PR DESCRIPTION
**Pull request by ayanozturk**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This project is no longer maintained, and I don't think it's accepting PRs.

**Comment by ayanozturk** [comment]
Alright. I already submitted a separate package to composer. I can continue the work on my fork. 

Thanks

**Comment by adammbalogh** [comment]
@ayanozturk Your pull request looks pretty good! I'll try to find time to review it and then merge it.

**Comment by ayanozturk** [comment]
@adammbalogh thanks! I have BC breaks on forked master branch now, as I added type hints on public methods. Ideally, I'd like to also upgrade to one of the latest container and router libraries as current ones it's using seem quite old, and blocking us to use Symfony 3.4+. Any suggestion on refactoring those?

**Pull request merged**
